const std = @import("std");
const lexfile = @import("lexfile.zig");
const dfa_mod = @import("dfa.zig");
const compress_mod = @import("compress.zig");

pub fn generate(alloc: std.mem.Allocator, spec: *const lexfile.Spec, dfa: *const dfa_mod.Dfa, compress: bool) ![]u8 {
    var buf = std.ArrayList(u8).init(alloc);
    const w = buf.writer();

    try w.writeAll(
        \\/* Generated by ft_lex */
        \\#include <stdio.h>
        \\#include <string.h>
        \\
        \\void *malloc(unsigned long);
        \\void *realloc(void *, unsigned long);
        \\void *calloc(unsigned long, unsigned long);
        \\void free(void *);
        \\
        \\int yywrap(void);
        \\
        \\#define INITIAL 0
        \\
    );

    for (spec.scs, 0..) |sc, i| {
        if (i == 0) continue;
        try w.print("#define {s} {d}\n", .{ sc.name, i });
    }

    try w.writeAll(
        \\#define BEGIN yy_start =
        \\#define ECHO ((void)fwrite(yytext, 1, (unsigned long)yyleng, yyout))
        \\#define REJECT goto yy_reject
        \\
        \\int yyleng;
        \\char *yytext;
        \\FILE *yyin;
        \\FILE *yyout;
        \\int yy_start;
        \\int yy_bol = 1;
        \\
        \\static char *yy_buf;
        \\static int yy_cap;
        \\static int yy_len;
        \\static int yy_pos;
        \\static char yy_hold;
        \\static int yy_hold_valid;
        \\static int yy_more_flag;
        \\static int yy_more_len;
        \\
        \\enum { YY_MAX_CAND = 64 };
        \\
        \\typedef struct {
        \\    int rule;
        \\    int end;
        \\    int cut;
        \\    int len;
        \\} yy_cand;
        \\
        \\static int yy_rj_n;
        \\static int yy_rj_start;
        \\static int yy_rj_more;
        \\static yy_cand yy_rj_cands[YY_MAX_CAND];
        \\static int yy_rj_ncand;
        \\
    );

    try w.print("static const int yy_n_rules = {d};\n", .{dfa.n_rules});
    try w.print("static const int yy_n_sc = {d};\n", .{dfa.n_sc});
    try w.print("static const int yy_n_states = {d};\n\n", .{dfa.states.len});

    try w.writeAll("static const int yy_sc_tbl[][2] = {\n");
    for (0..dfa.n_sc) |sc| {
        try w.print("    {{ {d}, {d} }},\n", .{ dfa.starts[sc][0], dfa.starts[sc][1] });
    }
    try w.writeAll("};\n\n");

    try w.writeAll("static const int yy_rule_dollar[] = {");
    for (0..dfa.n_rules) |i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{d}", .{@intFromBool(dfa.rule_dollar[i])});
    }
    if (dfa.n_rules == 0) try w.writeAll("0");
    try w.writeAll("};\n");

    try w.writeAll("static const int yy_rule_tc[] = {");
    for (0..dfa.n_rules) |i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{d}", .{@intFromBool(dfa.rule_tc[i])});
    }
    if (dfa.n_rules == 0) try w.writeAll("0");
    try w.writeAll("};\n\n");

    if (compress) {
        const packed_tbl = try compress_mod.pack(alloc, dfa);
        try w.writeAll("static const unsigned char yy_ec[256] = {");
        for (packed_tbl.ec, 0..) |v, i| {
            if (i != 0) try w.writeAll(",");
            try w.print("{d}", .{v});
        }
        try w.writeAll("};\n");
        try w.writeAll("static const unsigned short yy_row[] = {");
        for (packed_tbl.row, 0..) |v, i| {
            if (i != 0) try w.writeAll(",");
            try w.print("{d}", .{v});
        }
        try w.writeAll("};\n");
        try w.print("static const short yy_nxt[][{d}] = {{\n", .{packed_tbl.nclass});
        var r: usize = 0;
        while (r < packed_tbl.nrows) : (r += 1) {
            try w.writeAll("    {");
            var c: usize = 0;
            while (c < packed_tbl.nclass) : (c += 1) {
                if (c != 0) try w.writeAll(",");
                try w.print("{d}", .{packed_tbl.nxt[r * packed_tbl.nclass + c]});
            }
            try w.writeAll("},\n");
        }
        try w.writeAll("};\n\n");
    } else {
        try w.writeAll("static const int yy_nxt[][256] = {\n");
        for (dfa.states) |st| {
            try w.writeAll("    {");
            for (st.trans, 0..) |t, i| {
                if (i != 0) try w.writeAll(",");
                try w.print("{d}", .{t});
            }
            try w.writeAll("},\n");
        }
        try w.writeAll("};\n\n");
    }

    if (compress) {
        try w.writeAll("#define YY_NXT(s,c) yy_nxt[yy_row[(s)]][yy_ec[(unsigned char)(c)]]\n\n");
    } else {
        try w.writeAll("#define YY_NXT(s,c) yy_nxt[(s)][(c)]\n\n");
    }

    try w.writeAll("static const int yy_naccept[] = {");
    for (dfa.states, 0..) |st, i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{d}", .{st.accepts.len});
    }
    try w.writeAll("};\n");

    try w.writeAll("static const int yy_acc_off[] = {");
    var off: usize = 0;
    for (dfa.states, 0..) |st, i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{d}", .{off});
        off += st.accepts.len;
    }
    try w.writeAll("};\n");

    try w.writeAll("static const int yy_acc_list[] = {");
    var first = true;
    for (dfa.states) |st| {
        for (st.accepts) |a| {
            if (!first) try w.writeAll(", ");
            first = false;
            try w.print("{d}", .{a});
        }
    }
    if (first) try w.writeAll("0");
    try w.writeAll("};\n");

    try w.writeAll("static const int yy_ncut[] = {");
    for (dfa.states, 0..) |st, i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{d}", .{st.cuts.len});
    }
    try w.writeAll("};\n");

    try w.writeAll("static const int yy_cut_off[] = {");
    off = 0;
    for (dfa.states, 0..) |st, i| {
        if (i != 0) try w.writeAll(", ");
        try w.print("{d}", .{off});
        off += st.cuts.len;
    }
    try w.writeAll("};\n");

    try w.writeAll("static const int yy_cut_list[] = {");
    first = true;
    for (dfa.states) |st| {
        for (st.cuts) |a| {
            if (!first) try w.writeAll(", ");
            first = false;
            try w.print("{d}", .{a});
        }
    }
    if (first) try w.writeAll("0");
    try w.writeAll("};\n\n");

    if (spec.header.len > 0) {
        try w.writeAll(spec.header);
        try w.writeAll("\n\n");
    }

    try w.writeAll(
        \\static int yy_grow(int need)
        \\{
        \\    int cap;
        \\    char *p;
        \\    cap = yy_cap ? yy_cap : 128;
        \\    while (cap < need) cap *= 2;
        \\    p = (char *)realloc(yy_buf, (unsigned long)cap);
        \\    if (!p) return -1;
        \\    yy_buf = p;
        \\    yy_cap = cap;
        \\    return 0;
        \\}
        \\
        \\static int yy_char_at(int p)
        \\{
        \\    int c;
        \\    while (p >= yy_len) {
        \\        if (!yyin) yyin = stdin;
        \\        c = getc(yyin);
        \\        if (c == EOF) return -1;
        \\        if (yy_len >= yy_cap && yy_grow(yy_len + 1) < 0) return -1;
        \\        yy_buf[yy_len++] = (char)c;
        \\    }
        \\    return (unsigned char)yy_buf[p];
        \\}
        \\
        \\static void yy_compact(void)
        \\{
        \\    int n;
        \\    if (yy_pos <= 0) return;
        \\    n = yy_len - yy_pos;
        \\    if (n > 0) memmove(yy_buf, yy_buf + yy_pos, (unsigned long)n);
        \\    yy_len = n;
        \\    yy_pos = 0;
        \\}
        \\
        \\static void yy_restore_hold(void)
        \\{
        \\    if (yy_hold_valid && yytext) {
        \\        yytext[yyleng] = yy_hold;
        \\        yy_hold_valid = 0;
        \\    }
        \\}
        \\
        \\int yy_input_char(void)
        \\{
        \\    int c;
        \\    yy_restore_hold();
        \\    c = yy_char_at(yy_pos);
        \\    if (c < 0) return -1;
        \\    yy_pos += 1;
        \\    yy_bol = (c == '\n');
        \\    return c;
        \\}
        \\
        \\int yy_unput_char(int c)
        \\{
        \\    yy_restore_hold();
        \\    if (yy_len >= yy_cap && yy_grow(yy_len + 1) < 0) return c;
        \\    memmove(yy_buf + yy_pos + 1, yy_buf + yy_pos, (unsigned long)(yy_len - yy_pos));
        \\    yy_buf[yy_pos] = (char)c;
        \\    yy_len += 1;
        \\    return c;
        \\}
        \\
        \\int yy_less(int n)
        \\{
        \\    int start;
        \\    yy_restore_hold();
        \\    if (n < 0) n = 0;
        \\    if (n > yyleng) n = yyleng;
        \\    start = yy_pos - yyleng;
        \\    if (start < 0) start = 0;
        \\    yy_pos = start + n;
        \\    yyleng = n;
        \\    if (yytext) {
        \\        yy_hold = yytext[yyleng];
        \\        yytext[yyleng] = '\0';
        \\        yy_hold_valid = 1;
        \\    }
        \\    return 0;
        \\}
        \\
        \\void yy_more(void)
        \\{
        \\    yy_more_flag = 1;
        \\    yy_more_len = yyleng;
        \\}
        \\
        \\static int yy_match_ok(int rule, int end)
        \\{
        \\    int c;
        \\    if (rule < 0) return 0;
        \\    if (!yy_rule_dollar[rule]) return 1;
        \\    c = yy_char_at(end);
        \\    return c < 0 || c == '\n';
        \\}
        \\
        \\static void yy_add_cand(yy_cand *cand, int *ncand, int rule, int end, int cut, int start)
        \\{
        \\    int i, len;
        \\    if (rule < 0 || !yy_match_ok(rule, end)) return;
        \\    len = yy_rule_tc[rule] ? (cut - start) : (end - start);
        \\    if (len <= 0) return;
        \\    for (i = 0; i < *ncand; i++) {
        \\        if (cand[i].rule == rule && cand[i].end == end) return;
        \\    }
        \\    if (*ncand >= YY_MAX_CAND) return;
        \\    cand[*ncand].rule = rule;
        \\    cand[*ncand].end = end;
        \\    cand[*ncand].cut = cut;
        \\    cand[*ncand].len = len;
        \\    *ncand += 1;
        \\}
        \\
        \\static void yy_collect(int state, int start, int p, int *cuts, yy_cand *cand, int *ncand)
        \\{
        \\    int i, n, off, r;
        \\    n = yy_ncut[state];
        \\    off = yy_cut_off[state];
        \\    for (i = 0; i < n; i++) {
        \\        r = yy_cut_list[off + i];
        \\        if (r >= 0) cuts[r] = p;
        \\    }
        \\    n = yy_naccept[state];
        \\    off = yy_acc_off[state];
        \\    for (i = 0; i < n; i++) {
        \\        r = yy_acc_list[off + i];
        \\        yy_add_cand(cand, ncand, r, p, cuts[r], start);
        \\    }
        \\}
        \\
        \\static void yy_sort_cands(yy_cand *cand, int ncand)
        \\{
        \\    int i, j;
        \\    yy_cand t;
        \\    for (i = 0; i < ncand; i++) {
        \\        for (j = i + 1; j < ncand; j++) {
        \\            if (cand[j].len > cand[i].len ||
        \\                (cand[j].len == cand[i].len && cand[j].rule < cand[i].rule)) {
        \\                t = cand[i];
        \\                cand[i] = cand[j];
        \\                cand[j] = t;
        \\            }
        \\        }
        \\    }
        \\}
        \\
        \\int yylex(void)
        \\{
        \\    static int ready = 0;
        \\    int *cuts = 0;
        \\
        \\    if (!yyin) yyin = stdin;
        \\    if (!yyout) yyout = stdout;
        \\    if (!ready) {
        \\        yy_start = INITIAL;
        \\        yy_bol = 1;
        \\        ready = 1;
        \\    }
        \\
    );

    if (spec.local.len > 0) {
        try w.writeAll(spec.local);
        try w.writeAll("\n");
    }

    try w.writeAll(
        \\yy_next_tok:
        \\    yy_restore_hold();
        \\    if (!yy_more_flag) yy_compact();
        \\    {
        \\        int start, state, p, c, ns, end, more, i;
        \\        yy_cand *cand;
        \\        int ncand;
        \\
        \\        more = yy_more_flag ? yy_more_len : 0;
        \\        yy_more_flag = 0;
        \\        start = yy_pos;
        \\        if (yy_rj_n == 0) {
        \\            if (yy_n_rules > 0) {
        \\                cuts = (int *)malloc((unsigned long)yy_n_rules * sizeof(int));
        \\                if (!cuts) return 0;
        \\                for (i = 0; i < yy_n_rules; i++) cuts[i] = start;
        \\            }
        \\            cand = yy_rj_cands;
        \\            ncand = 0;
        \\            state = yy_sc_tbl[yy_start][yy_bol ? 1 : 0];
        \\            yy_collect(state, start, start, cuts, cand, &ncand);
        \\            p = start;
        \\            for (;;) {
        \\                c = yy_char_at(p);
        \\                if (c < 0) break;
        \\                ns = YY_NXT(state, c);
        \\                if (ns < 0) break;
        \\                state = ns;
        \\                p += 1;
        \\                yy_collect(state, start, p, cuts, cand, &ncand);
        \\            }
        \\            if (cuts) { free(cuts); cuts = 0; }
        \\            yy_sort_cands(cand, ncand);
        \\            yy_rj_ncand = ncand;
        \\            yy_rj_start = start;
        \\            yy_rj_more = more;
        \\        } else {
        \\            start = yy_rj_start;
        \\            more = yy_rj_more;
        \\            cand = yy_rj_cands;
        \\            ncand = yy_rj_ncand;
        \\        }
        \\
        \\        if (ncand <= yy_rj_n) {
        \\            yy_rj_n = 0;
        \\            if (yy_char_at(start) < 0) {
        \\                if (yywrap()) return 0;
        \\                goto yy_next_tok;
        \\            }
        \\            c = yy_char_at(start);
        \\            fputc(c, yyout);
        \\            yy_pos = start + 1;
        \\            yy_bol = (c == '\n');
        \\            goto yy_next_tok;
        \\        }
        \\
        \\        end = cand[yy_rj_n].end;
        \\        if (yy_rule_tc[cand[yy_rj_n].rule]) end = cand[yy_rj_n].cut;
        \\        yy_pos = end;
        \\        if (end > start) yy_bol = (yy_buf[end - 1] == '\n');
        \\        yyleng = more + (end - start);
        \\        if (start - more < 0) {
        \\            yytext = yy_buf;
        \\        } else {
        \\            yytext = yy_buf + (start - more);
        \\        }
        \\        yy_hold = yytext[yyleng];
        \\        yytext[yyleng] = '\0';
        \\        yy_hold_valid = 1;
        \\
        \\        switch (cand[yy_rj_n].rule) {
        \\
    );

    for (spec.rules, 0..) |rule, i| {
        try w.print("        case {d}:\n", .{i});
        const action = std.mem.trim(u8, rule.action, " \t\r\n");
        if (action.len == 0) {
            try w.writeAll("            break;\n");
        } else if (action[0] == '{') {
            try w.print("            {s}\n            break;\n", .{action});
        } else {
            try w.print("            {s}\n            break;\n", .{action});
        }
    }

    try w.writeAll(
        \\        default:
        \\            break;
        \\        }
        \\        yy_rj_n = 0;
        \\        goto yy_next_tok;
        \\
        \\    yy_reject:
        \\        yy_rj_n += 1;
        \\        yy_restore_hold();
        \\        yy_pos = yy_rj_start;
        \\        goto yy_next_tok;
        \\    }
        \\}
        \\
    );

    if (spec.user.len > 0) {
        try w.writeAll(spec.user);
        try w.writeAll("\n");
    }

    return buf.toOwnedSlice();
}
